curl http://localhost:8080/api/create_wordlist/German%20Colors
curl http://localhost:8080/api/add_word/1/gelb/yellow
curl http://localhost:8080/api/add_word/1/schwarz/black
curl http://localhost:8080/api/add_word/1/weiss/white
curl http://localhost:8080/api/add_word/1/blau/blue
curl http://localhost:8080/api/add_word/1/grune/green
curl http://localhost:8080/api/add_word/1/rot/red
curl http://localhost:8080/api/add_word/1/dunkelblau/dark%20blue
curl http://localhost:8080/api/add_word/1/hellblau/light%20blue
curl http://localhost:8080/api/new_question/1
